[package]
name = "printcraft-ui-egui"
description = "The egui shell of PrintCraft"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
printcraft-engine = { workspace = true }
printcraft-render = { workspace = true }
egui = { workspace = true }
egui_extras = { workspace = true }
eframe = { workspace = true, features = ["default_fonts", "wgpu", "accesskit"] }
serde = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rfd = { workspace = true }
